INSERT INTO EMPLOYEE VALUES(101,'Ruth', 'Principal');
INSERT INTO EMPLOYEE  VALUES(102,'Leyla', 'Counselor');
INSERT INTO EMPLOYEE VALUES(103,'Lola', 'Teacher');
INSERT INTO EMPLOYEE VALUES(104,'Lidya', 'Nurse');
INSERT INTO EMPLOYEE VALUES(105,'Leyla', 'Counselor');
INSERT INTO EMPLOYEE VALUES(106,'Nas', 'Test');